name: LZ config deployment

on:
  push:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: List Files after checkout
        run: |
          pwd
          ls -al
          env
