name: Shall Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline command
        run: |
          node -v
          npm -v
      - name: running on python shell
        run: |
          import os
          import platform
          print(os.environ['PATH'])
          print(platform.processor())
        shell: python